language: android
jdk: oraclejdk8

before_install:
 - chmod +x gradlew

notifications:
  email: true

branches:
  only:
    - master

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.0
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  ./gradlew clean build
