language: android
jdk: oraclejdk8

notifications:
  email: true

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27
    - android-27
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - yes | sdkmanager "platforms;android-27"

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script: ./gradlew clean build
